import { Metadata } from 'next'

interface ShowcaseLayoutProps {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: 'Showcase',
  description: 'Generated by create next app',
}

export default function ShowcaseLayout({ children }: ShowcaseLayoutProps) {
  return <>{children}</>
}
